name: evo_systems_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.1.0
  carousel_slider: ^5.0.0 
  cupertino_icons: ^1.0.8
  translator: ^1.0.0
  devicelocale: ^0.7.1
  flutter_locales: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:  
  uses-material-design: true